name: Sync LeetCode

on:
  workflow_dispatch:
  schedule:
    # Runs once daily at midnight UTC
    - cron: '0 0 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync LeetCode Submissions
        uses: joshcai/leetcode-sync@v1.7.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          leetcode-csrf-token: ${{ secrets.csrftoken }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          destination-folder: my-submissions